# Site
repository: deepmaniyar/deepmaniyar.github.io
# favicon: images/favicon.ico

# Personal info
name: Deep Maniyar
title: Data Scientist 
email: deepmaniyar@outlook.com

# Social links
github_username:  deepmaniyar
linkedin_username: deepmaniyar


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Deep and I'm a Master in Applied data Science student. With 2 years of experience in sales, marketing and analytics I have developed skills to understand business requirements and with my academic experience I have developed data analytics and machine learning skill to address this requirements using data-driven insights. I have worked at a number of companies, student organizations and project teams gaining teamwork and leadership skills.

  I am most skilled in: <mark>Python</mark>, <mark>Machine Learning</mark> and <mark>Eating any kind of food</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data science and machine learning some of my other interests and hobbies are:
   - Football (European one)
   - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
